services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.1
    user: root
    volumes:
      - ./:/usr/share/filebeat/config
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - elk

networks:
  elk:
    driver: bridge
