services:
 elasticsearch:
    image: elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      # - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 512m

    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk



 kibana:
   container_name: kibana
   image: kibana:8.11.1
   environment:
     - ELASTICSEARCH_HOSTS=http://localhost:9200
     - KIBANA_PASSWORD=password
   ports:
     - 5601:5601
   depends_on:
     - elasticsearch

   networks:
     - elk
 

volumes:
  esdata:

networks:
  elk:
  
    