- name: Ensure directories exists
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: '0644'
  loop:
    - ~/compose/efk

- name: Ensure docker-compose file has been updated
  ansible.builtin.template:
    src: "{{ item }}"
    dest: ~/compose/efk/
    mode: '0644'
  loop:
    - docker-compose.yml
    - Dockerfile
    - fluentd.conf


- name: Ensure efk compose files are up
  community.docker.docker_compose:
    state: present
    project_src: ~/compose/efk/
    files:
      - docker-compose.yml
